### ISSUE TITLE
Question: Does Alta has importing libraries system-wide?

### ISSUE THREAD

**Issue by ghost** [alta-lang/alta#21]
@facekapow 

Does Alta has importing libraries system-wide?

**Comment by facekapow** [comment]
Could you clarify a bit on what you mean by "importing libraries system-wide"?

If you mean being able to write code that uses functions and structures from them, then yes, Alta supports this. For (limited) examples of how this is done, you can checkout the standard library&mdash;particularly the `libc` and `posix` packages. Those packages provide declarations for libc and the standard POSIX library, which lets Alta code be aware of the functions and structures in them and use them.

If you mean handling the task of finding those libraries and their headers and linking to them (which is a goal I have for the compiler to be able to do eventually), I'm afraid Alta's not quite there yet. But it *does* use CMake to actually compile everything, so if you're familiar with that, you can edit the `CMakeLists.txt` it generates to add the libraries to the targets.

---

I'm terribly sorry about the current state of the documentation; I haven't had much time to get around to doing it. I'm getting ready to do another major pre-1.0.0 release, v0.7.0 (I've added a **ton** of stuff since the last release), and I hope to update the documentation and add more in-depth examples for that.

**Comment by ghost** [comment]
@facekapow 

I mean, does Alta has libraries path like C/C++ in `/usr/include`?

**Comment by facekapow** [comment]
Do you mean system-wide Alta packages? That would only be the standard library, at the moment. Any other Alta packages have to be placed into a local `alta-packages` folder. I'm going to flesh out the package system and implement a package manager later, once I get working HTTPS written in pure Alta.

---

By the way, thanks for your interest in Alta! It's not practically usable at the moment, but I hope to keep improving on it and adding features and eventually get to a stable 1.0.0 release.
